config/routes.rb
Rails.application.routes.draw do
  
  get '/index', :to => 'rooms#index' 
  patch '/index', :to => 'rooms#updateur' 
  get '/users/new', :to => 'users#new'
  post '/users/new', :to => 'users#create'
  post '/sessions/new', :to => 'sessions#create'
  delete '/sessions', :to => 'sessions#destroy'

  get '/setup', :to => 'rooms#new'
  post '/setup', :to => 'rooms#create'
  patch '/setup', :to => 'rooms#update'
  delete '/setup', :to => 'rooms#destroy'

  get '/tournament', :to => 'tournaments#show'
  get '/join', :to => 'rooms#userroom'
  post '/join', :to => 'rooms#createur'

  get 'tools', :to => 'games#tools'

end

app/views/shared/_flash_messages.html.erb
<% if flash[:notice] %>
	<div id="notice"> <%= flash[:notice] %> </div>
<% end %>
<% if flash[:error] %>
	<div id="error"> <%= flash[:error] %> </div>
<% end %>

app/views/shared/_make_calendar.html.erb
<% calendar ||= Calendar.new %>
<% monthdate = calendar.calendarStart %>
<br>
<div class="col-md-4">
	<%= link_to "Prev", setup_path({:prevMonth => calendar.prevMonth}), remote: true %>
</div>
<div class="col-md-4" align="center">
	<%= monthdate[1] %>
</div>
<div class="col-md-4" align="right">
	<%= link_to "Next", setup_path({:nextMonth => calendar.nextMonth}), remote: true %>
</div>

		<table class = "table table-striped">
			<tr>
				<th> Sunday</th>
				<th> Monday</th>
				<th> Tuesday</th>
				<th> Wednesday</th>
				<th> Thursday</th>
				<th> Friday</th>
				<th> Saturday</th>
			</tr>
			<% monthdate[0].each do |c| %>
			<tr>
				<% c.each do |w| %>
					<% room = calendar.roomInfo(w,(current_user ? current_user.id : 0)) %>
					<td class=<%= ("calendarJoin" if room && room[4]) || ("calendarSuccess" if room) %>> 
						<%= (hidden_field_tag 'info', room[1]) if room %>
						<%= (hidden_field_tag 'id', room[0]) if room %>
						<%= (hidden_field_tag 'games', room[2]) if room %>
						<%= (hidden_field_tag 'gameIDs', room[3]) if room %>
						<%= (hidden_field_tag 'vote', room[5]) if room %>
						<%= (hidden_field_tag 'weight', room[6]) if room %>
						<%= (hidden_field_tag 'uservote', room[7]) if room %>
						<%= w %> 
					</td>
				<% end %>
			</tr>
			<% end %>
		</table>
<br>
<br>
<br>

app/views/shared/_navbar.html.erb
<% current_user %>
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <ul class="nav navbar-nav">
      <li class="<%= 'active' if current_page?(index_path) %>"> <%= link_to "Main", index_path %> </li>
      <% if current_user %>
        <li class="<%= 'active' if current_page?(setup_path) %>"> <%= link_to "Setup", setup_path %> </a> </li>
      <li class="<%= 'active' if current_page?(join_path) %>"> <%= link_to "Join", join_path %> </a> </li>
      <% end %>
      <li class="<%= 'active' if current_page?(tools_path) %>"> <%= link_to "Boardgame Tools", tools_path %> </li>
      <li class="<%= 'active' if current_page?(tournament_path) %>"> <%= link_to "Tournament Builder", tournament_path %> </a> </li>
    </ul>


    <ul class="nav navbar-nav navbar-right">
      <li class = "dropdown"> 
      	<a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= logged_in? ? (current_user.name) : ("Log In") %>
        <span class="caret"></span></a>
        <ul class = "dropdown-menu">
          <%= render 'shared/navbar_login' %>
        </ul>
    </ul>
  </div>
</nav>

app/views/shared/_navbar_login.html.erb
<% if logged_in? %>
  <li> <%=link_to "Log Out", sessions_path, :method => "delete" %> </li>
<% else %>
  <li>
    <%= form_tag sessions_new_path, :method => 'post' do %>
      <%= label_tag "Username" %>
      <%= text_field_tag :username %>
      <%= label_tag "Password" %>
      <%= password_field_tag :password %>
      <%= submit_tag "Log In" %>
    <% end %>
  </li>
  <li><%= link_to "Register", users_new_path %> </li>
<% end %>

app/views/shared/_players.html.erb
<% @players.each do |p| %>
<%= p %>
<br>
<% end %>